apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mealie-backup
  namespace: mealie
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: nfs-backup
  resources:
    requests:
      storage: 5Gi
