apiVersion: apps/v1
kind: Deployment
metadata:
  name: mealie
  namespace: mealie
  labels:
    app: mealie
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mealie
  template:
    metadata:
      labels:
        app: mealie
    spec:
      containers:
        - name: mealie
          image: ghcr.io/mealie-recipes/mealie:v3.14.0
          ports:
            - containerPort: 9000
          env:
            - name: ALLOW_SIGNUP
              value: "true"
            - name: TZ
              value: Europe/Zurich
            - name: BASE_URL
              value: https://mealie.organa.one
          volumeMounts:
            - name: data
              mountPath: /app/data
          resources:
            requests:
              memory: 256Mi
              cpu: 250m
            limits:
              memory: 512Mi
      volumes:
        - name: data
          persistentVolumeClaim:
            claimName: mealie-data
