apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: mealie
  namespace: mealie
  annotations:
    tailscale.com/funnel: "false"
    gethomepage.dev/enabled: "true"
    gethomepage.dev/name: Mealie
    gethomepage.dev/description: Recipe manager
    gethomepage.dev/group: Productivity
    gethomepage.dev/icon: mealie.png
    gethomepage.dev/href: https://mealie.lungfish-ide.ts.net
    gethomepage.dev/app: mealie
    gethomepage.dev/pod-selector: app=mealie
spec:
  ingressClassName: tailscale
  rules:
    - host: mealie
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: mealie
                port:
                  number: 9000
  tls:
    - hosts:
        - mealie
