---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: mealie-secrets
  namespace: mealie
spec:
  encryptedData:
    oidc-client-id: AgAPlPFu050HfY+hODn98U6jB8CDq80s2z3EvWJocpLgEudwM+L0NMlR8VsAdiOX9bXPN3JJy397/YYEUImb6SuhN8WrL1eBxayXULDdn/pQDwy3SjkwlsM6Yq5ieI51E1zuf/esKGJCcHZcix/Fy0KSFxZnm8mRJroTlubjtlpWmwvmtPYktQ64Wjx8uGD2PR7W90QpSGKCb5kg84/wI1YKjWyaTZ8pOBTZmdub4iPls+E/HiPToxK0AQay7evB5VCzhf5eCgJB+TqcnUcYkd1a19cAO+7CioQ9swbMeBZ0nUvEy5TW/pXnIjVDDDv8la5AWR+a76dkJSr25MdGB9xUTEBPPtoXp6RVwoK2fzzvHxwzOKqXRhjKQNSpyPxEt7WZ76w4iMZ4XogMoU1NB1yFLqIR0Fi5Qg9bMH9U7ITnRrHvj7lxueahDJAMR3UD+1Umo24lVj6Bsc1Bnsc6zzP3PkNAXI+yx+7gpBX2fm8KAtysJgz7FG1fvmHMW7UGuw9vb3Jem1OQ2ZMkJIK9tIBgzLXQzudBmJitj44RTYg3yOb48vx+YduL68gJUuSh14ACBMpZHyn0XUzSfN3J1SgHJrdDjdb48JGtMECVUE+Fsf6Sy8YLkQfR3f8kpHF9AdROrH0R1fMD17h4bimFrNGeARZyXQnZIbmdFjkDhFcb8TLJEY+RKLMfAcbKTVKgyJmf5lfjnj4fUggEMw4SH2n7OtoWCfL5YZiJcCclfFa/uTmmfFRc9+hH
    oidc-client-secret: AgBK9nA2RXhGNxeIEUTTyfnjIhpF6oqUKabsoR0HPIXsNLVYUVw2Hpu9OK28hm+0fiYmZcklbyKYRcaqHte56IALItuz1ORPVpFbapyB88+W7CBP3FfQVjHb1kysyu3m3P35WNdq9aXQJ/aDBNreAeys36StkB8+bLo8jQZs8GuyOAMYpawmJLuqDMmeyljMXO9hGTl+/n23pxY3O6V21Tcaeg8Cu2AwB5bhFFVS5cbE2iY7WgBoXtbbXohPBh2SKrUrTx9gmrlNr9qmHow9SPBq+/M/A3hHDuVQQdAwuguwIXrEAFwT56LPAdga2iRU9y2ckBs1/Ok7dqwqMLZl8dtfkR7TN6xchE/Dhq84QiUAKwI3f5rOD15cfQRMIQuKMd9hK9oZfdr34+ypXe95fZAglAosKnmZqPjxi25GC2egEk/NKLSYuVIzOoJhBhC/PEWb7YgZYXqxsk54uAxhzsYZc/h3Ht0BjH0wpdeG7raApBO5T4BqhCzZcETQUMKWIgdxXoQL/rOZRXRqWxTz6cZWMV8guDlmvMkMWCmj36akqwUrIUocMSkG4wQPjv+xhAkwfFWyinQOzLIC/4BpIslsel0oMb6cNS7ND5tdMp/9wiDpY8hOXwYzjQ8EpvEmrZeGa3Am+VKKx1Y8tVzr5XIC6tCFleh9+4Dx8jrqd/Fm+C6dbKtOUvia6rusAqbMy9dRVkWZutgJrcamNqUODK4m3a1Ir7g4bhgiQMTB1ug9H4ppoTD9l8CHuxXFWuMO6rNtRBfmgnAkoA43ZR4/bfEhq6aTP4TONTxQl+9H35+LKb43aChdCWdbkGgpmnK7GwHe+OnI8a5zMs0rT4ECa6c/IH9wpqECUKkuO0dRKZi7lw==
  template:
    metadata:
      name: mealie-secrets
      namespace: mealie
    type: Opaque
