title: Homelab
favicon: https://cdn.jsdelivr.net/gh/homarr-labs/dashboard-icons/png/kubernetes.png

background:
  image: https://images.unsplash.com/photo-1672288072591-619afe830096?ixlib=rb-4.0.3&ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&auto=format&fit=crop&w=1920&q=80
  blur: sm
  saturate: 50
  brightness: 50
  opacity: 60

theme: dark
color: slate
headerStyle: clean
fullWidth: false
cardBlur: md
hideVersion: true
target: _blank

layout:
  Productivity:
    style: row
    columns: 2
    icon: mdi-briefcase-#64748b
  Infrastructure:
    style: row
    columns: 2
    icon: mdi-server-network-#64748b
