- datetime:
    text_size: xl
    format:
      timeZone: Europe/Zurich
      hourCycle: h23
      dateStyle: short
      timeStyle: short

- kubernetes:
    cluster:
      show: true
      cpu: true
      memory: true
      showLabel: true
      label: Cluster
    nodes:
      show: true
      cpu: true
      memory: true
      showLabel: true

- search:
    provider: custom
    name: Ecosia
    url: https://www.ecosia.org/search?q=
    suggestionUrl: https://ac.ecosia.org/autocomplete?type=list&q=
    showSearchSuggestions: true
    target: _blank

- openmeteo:
    label: Basel
    latitude: 47.5596
    longitude: 7.5886
    timezone: Europe/Zurich
    units: metric
    cache: 5
