- kubernetes:
    cluster:
      show: true
      cpu: true
      memory: true
      showLabel: true
      label: Cluster
    nodes:
      show: true
      cpu: true
      memory: true
      showLabel: true

- search:
    provider: duckduckgo
    target: _blank

- openmeteo:
    label: Basel
    latitude: 47.5596
    longitude: 7.5886
    timezone: Europe/Zurich
    units: metric
    cache: 5
