apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: forgejo-backup
  namespace: forgejo
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: nfs-backup
  resources:
    requests:
      storage: 15Gi
