---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: forgejo-secrets
  namespace: forgejo
spec:
  encryptedData:
    database-password: AgCROnZyNRJZvryrdohEZudfFk+8+VkuBuj5XsXyQ0gu1+SpzLOz0GuyYATYRqVmDs9MM/lwJ8QUtd0nJ6mhUjimSqxnI26jIfvB7Hnd7StnWDDjIKVVVR/je9A/IfwCMckiAsEth69eqzQFnT5nuC9TnOq0+7sZvclJSXSPLP34DkvAoNkFFMc88aFRNGK5r72ux6B+qvLN9+RkeRO7aJJe/hvETAhor4KBOy0TjrpsU600Tgj0zjEZ9FFF6Fg0sfUIvTeEWFj5jvX3gP47OSD30iSB5B4d5hYVZDg5RtfQIpTGqa23K7rg3EJILh9maNOVe5+zpYbInoq04UKbxDSR6i0jEq3NU6uuL1sUkr8iWHXNSynP+7nYAKYsVNo5Hr6HOZ4Kx3kZ8bUkYzVK3mY8UW8qYIv6dAxYn/3lZiKdBZUh4MmFMMCdYO/dSd78b0ia7L2hkksHLQ1G8lQMTdCxzUoH+Fgs4LPpiVQmWvDw4r66iC1V6yBKq0/mIzsbVw4S9AY+Ol0pchcfR+D6Gkluh6revAcVqLWDjcrBq50Key5TUT1S6I9Dyhrog2A3sM9mQd+e9JTPzxfu/qc6f6c2Z+sr75vjmbWeV87EaEqmCrjEq+0mno3BZr7kE8JuDx+GMPsV+rEk6EQd3D0MEsEncU/kiXMCTjizt9ypRD9qNJzaFwstDxDtDreGV/NwFzTlUIkJVYr8A3GeAud7M8FYL1xNqPiAenGLYrBpMrXW5vGO31CE4OIhsA6TWQ==
  template:
    metadata:
      name: forgejo-secrets
      namespace: forgejo
    type: Opaque
