apiVersion: v1
kind: Service
metadata:
  name: forgejo
  namespace: forgejo
  labels:
    app: forgejo
spec:
  selector:
    app: forgejo
  ports:
    - name: http
      port: 3000
      targetPort: 3000
      protocol: TCP
    - name: ssh
      port: 2222
      targetPort: 2222
      protocol: TCP
---
apiVersion: v1
kind: Service
metadata:
  name: forgejo-postgres
  namespace: forgejo
  labels:
    app: forgejo-postgres
spec:
  selector:
    app: forgejo-postgres
  ports:
    - port: 5432
      targetPort: 5432
      protocol: TCP
