apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: vikunja-backup
  namespace: vikunja
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: nfs-backup
  resources:
    requests:
      storage: 5Gi
