---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: vikunja-oidc-config
  namespace: vikunja
spec:
  encryptedData:
    config.yml: AgC+7Cbqa2YPe9VJfSrXDZnlc921/woR7NBtGZs7XMyWZWMj2vk15qdnFDsQNua8zWYOP/fYslHGq7xjc86hR2KUST2sKAL+b5OAQKmDUYaD5UpSPWn/qzbfj7EZKSiZn68zIixMds0L8KiHzI4iV9H0uH6M8vqI4FURlmLLR0tzfEpoDNF+OkrN6zNyhAk2MYcccF1P45yOl1yugX5TAwpc1JQ3O2/Tg5aNf29zztKCxS9V0N8XydmMp1wdWAwUz3YVJu8NmAMzhkxbMeKhEpf0e/1f0+84eugLh3QxxglCLOrVPg1tXCQcwmS9rv6CeRMus7P3oNJq+QTFisxmLY3aIgQsblyp79yTMtmGwQQd6Vai1cXk9Vdz1I1WicP8IX/iq5STe20K8B1CYaGW3sNdqPaZX/7dTiBYZIqMelNb++xlJfXIqqBnpTUJNAIhiX8/98+BGv/3bKKwTV6cIhq8PmeoHBItG2tTmw75BZxdX6m7uby603U9wCknYdDS5VzKC8a2hmYRoJWduPl/2ehkY4uZcqvj0W4s72woBiBSAOyKH9p3tb1ky8xRZEIRZSWIdYkkNH/xbOo3FndVJVzkzcYVS/DbdrcLWx3/8uTR3PR8ojch7o3FvNIrdHzGrPOjd1rFPPj+jNzLiJp/3TI8a7MObX8q6ObKsNdmdhU3qcDkqmTWpwxiLR4OmO14QcviwLDgZFBNyKHTPNnAkk7bwrcsSQstbw+0WSIQ/ctY7xST9em6X8I6w55kKC34PCFLCU68AWpDa+jswVWJKlNiiIem/KXO7IzTuawzWpUzPitcyG/QQvmudzp4t5Gm0so/UFXekHPRi2hyD1V1kPGR7EGekTLWiRz0/KmdxmGCs8Bxfkp2Tfyo5gCWWZK+m+rQtD4FQNQFHdGG9yQ69BEmEWOST02pjtXHZEdvBLCzmD2KTYCC3WmxOwYzgTIoRYDDwHHby7X2nlzbWSvorSfZK2LGmS8HNmqdpHxb0imqOzYjxZv/G8PZOabfwcJ0knmXeTe1A+tzU69bmcoVNsvtxdmQz44XSvvz2NSE5LJfSGbFuNaH0Cfq9bxC0hGndPXC1XogoJQzzV4rc2spTL4lcB+FRq7WjUe00BRk8dggWsa1lHbjimLR1O3QcQw9GIGgbH7v+qEYpzNkgsf5Mqr84scIvvA7oocEic+sEzrP6LEe6MFI7GRaPRaXJyROYAyHEQDRXSd4JYVajBwMQAfz6wxYc32Bqp+ZXzbOWqBRsC5iEqp0I1QASEqeHVEF+mlL3N97isSFxhHvsUAkMVm/R0MYns9Yzr71lqKEPIeylIaNLerbN6Plv+q13LAONr3G5gXVFhwHAF1TU+ML3JFaMGTnsu6bJHkpL0PWtuaSS6uDg14zIrisiofwuF5DieQnUrym+zuze/ElNQ==
  template:
    metadata:
      name: vikunja-oidc-config
      namespace: vikunja
    type: Opaque
