---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: vikunja-oidc-config
  namespace: vikunja
spec:
  encryptedData:
    config.yml: AgB1LEKJBog2E3YHDtFs61O4VuX5NrP0RwhbYudkNGSw37iUErSVwf6kXBEWdEtZh8QqSN8wnUkSGghv9V5+1VLSsaZr/S6t+kslrAkG0VBdqJDo4njcZMzh9E3zybzJs5w4k0gmCZCdWVpctRjuoTBqbuUqrhpAe1Tu32QY/D/BBzvg/fnrTaGtV1WYgm6vHL1kr4QWKkheBS5+cuSRLss5qKpnHL7MyDq8K7okVo95gZ8N2ZtoxFtazrLpHn7nUQqQrXcfwhjq9/Ro7aB7K9koJRQc/lJYdO5egvyH69tcXIJ0goro+vx/vTE2df/UTNbMiQW1O/qAY/X9Q46K5hObA1lggoUurYmL98T4Hx+kMEfT/f/OSLoTT+EAwInbXRFJ8VbzlUZaB9fgWWrnkf2niOI2SypXnUSkTYwA4mB2+qhbViXcUBJJAQRZXi8Z9gp2mkA+ug4/H1ALy0wnQRzWfyjT0fEIklVkQpRP8yJ6DvXD2hNHz5XGFv2FYszSkYzuG5Q/9CiIcspV61PAG/2y1yLEYP44BD53ccIqsuMGjWltCyG8vVWiNqxp8UXKOXCP4NJC4LIhOBfoIKfUYMy3rw6XtiWOgNC+ZtJc+8E3OWDzwJSbWLC9KeoSL5G5HduY8kDW9/sPtMLnE54FXxl5q6VzhN+xg/wmpPhGElmvcxCzj8od7Uv115sdOPv7CsFsix5J7HGpT9Lxw2yW+Pja79vPCyHIh6gZw4+KdWfqDN5c6xxGACrT+gFSuvT1vqfoZfcejZKwrAX9c/484BkT2tag/su/BCOuPijP/lzjWpcKSXAvV3B8hqtZ8zcrDH3V0uRAtvnMXOpBWG6i25HpJUtfZfnGxMh7WGSTawLgOOI33werT4EKUo8dHBHcjgYKBZNm41l+rySM4F0k9XmXGBW11owOfjeoazyMyE65axaUG5g69gY+j/GDRN2dZ0PddELEXTEaI7A/IBwd32Xws5XrfaxmTwohM4uVf5MiOaygR39a/OEjBiwE8wQHaDD0niKcFHj1x/fuw82hW3uMB9gaFHiVLyU24rxXRAu4KBEXsfYPpTVoibE1DCYbHRZ6FG0DmMWPVPxEKabJZXAMs5EuCcoVTRuQeUwlZrLn9uok909CSReJmnqOdoJxYdbeAagQJjwh8gO578xJsJT9+HPZHhWs0gR0RonxSd4mU7icGCxnFqhuuRV0AN7MrXtu9hCj0RvM+pAP8EhsXUMSsvbGCLYwVW+3sivS3/RfD00hbIoTFpLOxHn8UPWc8YmLrPBUPg49G2W+NwWviiT4tQiBmNPo0zjkbAnsulvzfbsSn/YnKNKuAesshZhnYORn60f7hOjuTQKPWahhZ/8eD+OborY93fYdICUthnuDs02iJmlXuDcdsK+ZO3BSimK6lLWSFL6fI+UvLw==
  template:
    metadata:
      name: vikunja-oidc-config
      namespace: vikunja
    type: Opaque
