---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: vikunja-secrets
  namespace: vikunja
spec:
  encryptedData:
    database-password: AgAtpAdsNf613nI8nEPvM9M+M95I+fAEP2031HBcA/Hoxm+G/6DvHW4GZz55yyKXnHS2H+tuG7Vwozx4jnUZI4KY3AtyY9JpzDRH3cBnP+snVmoY2wAiU+IW3uC7y1vis/7CIEcozvrZYVpQK+FRebaPnB27CQFXQL3kvnszJ+bdiT9sC77Ff0Ei5f1944mIobEAn3EmsquXcK2OJbRdIWjtqI3E+HKY4pgllpyp1jljEA9+HNc4BizPWSzwaZdRjXwHsFBEn4e7acoNjzAHorDxtFH+tKMKvn7dXaZNZDEcKAQN9v5ifPwygUyajT0hBjsmh8aEF7LMMCjuai60dK3thcOinD0wXV+/AaC9s57uK6dft1egaH2FN94E6FFY+dBigXgDIVObY8n7cUSP5JoB+g/3AnLadMZbUUbIjtvKuPwsTX7MSwLpWcPIYWLT1WLx2Fuj7zQfO0l+YLYW3/SOdq7G9jOeJccyDqbjriPf3L7n5HSgxUp1A5ByuvA5/EZ7p2ZagBaMgLnKxet52bhn4ycauog0sHPvHgn20dtJqdBzkwSAowPD6Bg5krx2lel3sb4X3x9IaEZOxYv8pJKNUpm8Q86RDnYkewg2ZZL/taoVXtWwjeaxvJWnadBGEktxA1GRUX1aUGf+wSAgJ5/r6n7Xhj0P0w5UewziYvFFdBjWSTUfhKoEAYpR2dmOclBlBXYgllSxMjWz4Xw7nbRImHyJCJ8VBcb9rd6WFXcjh7l8bBhHtVcbqUGYvufshPK54saSPueY9Z3+3iWBO4PT
    jwt-secret: AgCCOvJWvnW5UtiIYqY9VogjtiWpvpC8iouNpjG8vzcTzBIEcfAav8kaRZbF3I7zc9E2WuIyQB3xTuCoD+mT4MRPSnnQYqBUDdiXNnNJGBdsnwyZhYD0wJ6fBLS7/k+O2wtKIGZnbtHvUyYERotbynZFuJ2qItRpehI6ltnZD2QWz83RJXwUB7ZYU92oJ+XxF0LThfMcWxT3N0YwzOabJoH8coY1/3zK7P5e+ojLGBH8PykWgWj8qxs3g6cdaTdDn9mEGEn+JJH98bpWbfp0CWgtPzYXCeFHW/2XrcJQfbs6ayqNZ/ly7/CaI5NJmJnWMj/dTBc2UfqiKFIEZFdJuy0d36ZjzyWYiB5ADlwdY/MyB0ld0BfGGLa4Obf/ZQekDRO0SQZryUoBMttVvKBHuYkP+PgpIziMl3kPfq3vIU7Z/FlR+Dj/fY1MoQWlqZxNw81mdYMKX74F/x4e3jAbX6Box2ykqZuI/QBrh9iLDZdoBsGbzpvxIgkDUKferVKteohWza35d0VQebQsZ2+pMyZnIEKcPHHLYnBKRInAw9CrA7H4azKZuHoaQSW+zdjDmhJVB8XV/OtrG2+ThipAU7RdgnLm82hDYq3bMXL27X2K3DnAdWdFx8MIvNHVXqU3reA4/AN5C3meFTj8oBIpE8sM1hMNz4N1WSxriikuwknjiusJvE321Z7aqccHUzNIK+y1UV2iUtYMz5DKXwGqvRzCOp/5ljmysrMyzck7BAMk6A2oYYymzaFJgiwIK9rb4h1Yr/COWWNKRmHeMWJS7V1G
  template:
    metadata:
      name: vikunja-secrets
      namespace: vikunja
    type: Opaque
