---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: forgejo-runner-secrets
  namespace: forgejo-runner
spec:
  encryptedData:
    runner-token: AgDC2r45FlnTen/HojixQmvumXO7wewAhoaXDVMSdaQHMwajkwyvgmII0kEf1hF/VEA3f1GuCYV5peNbA0Sf587WFcUeA9NN+Ppd2hIGPyh5GWB539A9SiuD4KVLAx3e9Lu/sJJF99wfLJhoQQ9wAQZBHRASGnmm1Q6D/xsgS1I0ZzoYHOaDgSz/KgOuLSWyhNZ2jvBonkp897eCReWIfBXtkJt/IuLCLR53HhXIwrkc0hkb6G6++tnfARZ6JsGIH9adpUmnF1H10zvHyjnKhADGjlBK4nS5JJxgNxENLw7FbMiWyBjaWdeEz4L+2Qhv0ZEmloyJ2l2JIi5s/aD8YybO/w85eYnUJZDPCEbgbv1moYWd5rfMovntxnjVFxFUSEmyZH3oysP/Z/FU9bXVSPpyteg8Q4QTc2lk+ts4HLn49okrV3DwS6vBdHXoqLDDi1oABXc49aotdF7uf8SO4d/NHxK9b/8/vVNw1twFKnOj8H7CoqzHXKVjNYLFTh0xjsmGBMfSZeDKpHXMGGywBQrrskyBLefqKTfrzyYkKB3lQffIE6CMCIH5GcOkM2lZ2zOhZVaoL0sSTlPYUtnsswCXBvXUHSzM9sdJU2mC/DwlM8Ff6//4vvtkIUljwwMgg2DwMEKJ7mwDQxrkNOX8gEAL4cGgnH39ED6pJUI6rWh60VMHQLaeY4D+ViDUcBXn07WqYDD18ucsTEPcnSpXycIibZkMWdbGTLLKVGpN7+1wRsLtyfkx9TFtesjY
  template:
    metadata:
      name: forgejo-runner-secrets
      namespace: forgejo-runner
    type: Opaque
