apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: authentik-backup
  namespace: authentik
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: nfs-backup
  resources:
    requests:
      storage: 2Gi
