---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: authentik-secrets
  namespace: authentik
spec:
  encryptedData:
    database-password: AgBq8yjEMK6f9jlfc+YmV7z7vc6oq6Mknc74EFooC24FDdtvZVSl3Q21E1r6WjJVvv2G7VTNG8Th9HaDUIhq6tHC66EH1b/yZm6Yvmu7TrXLWA0NmdUrCP2+WqrzTqyImrVJ+4Fp1/iOLitTUQIF+UeR6YbMjqMWqH+ucIwjWCZXLFU72gOyVIdXVZ/2ZXZ/Gk7ofjODV8kSP8t681WFxxOD6tvmkdjkGNseCjpMTTxGIsvyyvU4UpUZkNDCoeRYoXmPqyeP17uahCSxtHNLbBwYUtf8dvitUxkAD8bcdFnjbpPwqbw8M72ITuQMfcVUXccL8yBSldWTeOFsGX9AmWzC4e8xhActLLpq+1WAyvUCqg/7auRZVdG026FUStgqF0d0k5ZyfFmm2cEXf7RYI9Dwi0wg8zouxZwzkMBP7sZqhDUT5PB5MPDhwbyOV+ScbYXBRzR/nLEa3nVv7vROZXptb7ul9ikDU0TZlwITA/EdvKkQlPyf054M+r6t0qarEOeNlHgn+dnQn7aYimHOErax0DR5GPcNiO4+3zWxHIwOCqyDDbQP36lFDGjcyYGv/9/FIHl1wV/bavBUDy80yxxfzo4V1oL5x67FtK4qSGug9TJVUneosNaDZjXiLpZwfl3TPYqlV18HFS3MqHN2vl0JlDgzB+ds4SUHix8xKt6IeVy/jGra+v6ckGWuU602dbv0U56aVR3SjHeA5yA+UInPobyrHmFMD88VnG2l7AJmi2m0pCHUM1yh0HqV7hUBxJ4=
    secret-key: AgBigMRJZ9Yf3dJvnVukbIZtlVBYJARxNOukeDRH50G7McgYML/ZjcF2O87sTVJ3HSuvqhuegqK3SMbZemaRKfBq2Xb3Pb0PpGNO1+GO/AVMUT+nA5ud7AhAPI7Kw8hug0mQYHxG9SHEXd+5Upg4u8/8kyQINwRsVxuAltj5ttQdINYb40jqYvY2D1YhNqzV3MFYRxiXd48v7vBdwPiL9/KT1ijuFV3ApYFg4n/zMFQPo+PrVRtV6/GjMq7a4+1aRmoTI9rMMruRO4YOYWDATFgX2Xp/4d23m1z1Z1JtP7IzUb0NgHZeZdEJqnIOgDAmU95N+8JNxxdEgnR9UzLbRBUroYD6wgLWIYc1mv9oxywtC0QPnQQj6kaUwSj7E8dfDYaC+wv2W6I+DfOoOaH0WbSXZuZxi0yFqQO8CRSrppLpGO/AuSnrGvPcew/tYlorGdUryGiWwQbpht7HiN7bNS2hlACdbDQ9NSdI+pa+J/pHHaRCdHbKfzDB/B0lHa1CCu5Oz9RzRnQjwKJ+VtucRY6QjDvAQHhm5ZJM5TC1NJNxFWXIw5vlOu0TltRu/avyiuEoZ03bNYpp57KPSOWj6G4ZQsNoSt1mstAhBk3TfiZfh4/zuISL3iIRlJjx3FHdMY71OwHPQVyEa9vyYoyeOugsC9A47FDaXSsWeGvN3kvjPPWTCWH7IWmMxl84m9d32BKWLpZ2474v0dTa41kHJgt1nvsNn8TyF56PU95F6i+C7Jar3PIOFkmTq7YafUFrj5tuWmwv227y4/Otst48kuR6grC9rCezkCBfAWKMm4qHnQ==
  template:
    metadata:
      name: authentik-secrets
      namespace: authentik
    type: Opaque
