---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: authentik-secrets
  namespace: authentik
spec:
  encryptedData:
    database-password: AgDNSMeshUfU90w6IvWbsAGsM57WCAPis8dgOAXoCPjp9D8Zdki3nqQV2RmfyEpbuqPVMzFxKHDhzbgRkTCBbWogr2Q934WipcH+OhrOkkeedTGeOCQ9pt3lLKt2YdMoy9PhMVAw7b1gHigHTWIJMnJ5KNJz5zp1vdBp7ySZzJrrAQbvHpcmBCfKdpSM5+u+koifJy8eu4qoCkQyw6ZmKjll72V3j5vCXNX/qqCBfScIMmZqvxV2TNfNYznUF6KnFeOB12yrxbrehZLH5OcQ/SfYrlpRVojFShqOJX6PkGa5A68WaqRRmkmH4uK7JziIUbDZ4A3NyJ6/FiCnAoT07FXHVY6RXAIf6mvDEFPWrYjT20nf4T9ACgLdolB8Am4mphe0Gx/Q7+gt1Uwh81zmMenc8KNORGedmoUfs0HJwa/6E5kvCIDhpqjLVYkYGEvika7pXizuqACK3kH8TPuDQ/bXEP6yo5B5j4Zzz0TF31RyKQaaFmLFFJXbnHalTM8HgLNAG/5RVsYv3H6UGYZmkyvW4rRvbCKSoFxCyzc63+V0+C4QINpdhe6zQQSwRJ93HwQpaMniWKGbj9Vt/1QdZwJQbHurLpobif8FWwDx7dfmdw+5jg9COes9h0FWCLeoCAkhX66EN0WWfmfApK+Z6Q+E+DGlyYtgMyYJm9N8kbjyKg1hEr9OcPR9gaHvf52EScVsLXDRIUweUZVfKRTbT8P8qpnej0xC68/eqR+Ra+fYkDXPfC9FwYBlCBw/Rg==
    secret-key: AgAGVdVYCfuBmlc4KgGOmasbn1esUOPzEJF8x4I2U2NlpKwyMaShCiLHeQG5ShMGlfJOyRA2QsZlxW16FdtQ7opUicFkqEawlXbXbVk6C44Ybsw6WZNLpfcowDKR6ABcpxGJekREHrYymCL3mQ71kig02aWMIHlpFJbuxd2I9RaWxpNojnrLSKVLbgUcYXZv+nJ0Zyom7RxmiM7tp3h6X0AGr2oDjs70Pauan9WLRLIJ+E5BIDxjrkCd59yXfC1jlwTUZcJKDlSzBUcbqN0n8RKQ4MGe8s4Fw8MugPP5F0DZFXmprgkCfJBT2WpwPO670CIh+5s8tPSUzMNy7r6XcOdS/7C5XT2TURL2maE+ROP2d5v+ZmCticUY9OYzTLbIrqgV4tK4aIKNSYwoG7sRUcwl3tHPLdC+y1bWHYXAZR96fo7sAMty8p+WM0M8bGAuZkCpxED54GfucDV2CdLVsGaJ9BnCOIsEiHv6l4mj1DOFArnaBMNlA1aZ3vHF8ZEd/lhdglpv1HRqLzsqQYRJKHbDUNA4f9Zn+evdsU0ayiz1dsWKEBjELRpmuA9wzuYuKCCpRLq+4LhWUnSTgmnX1bOGMP1gtAGixEK+3yYtMPfssFCT3PR8obMo4dALEW2bmpI12vR2YlAovW+vm8wWuoB0d6Roi55SHK+nVwAAwgcpYvThK19kSH8kX60CGdfCc+1DqjAgpb8Qx+XYaBk54Gvbcv0Bg8nuhgiozsc7vhuolBmYbRmT7Ha+1PDsxZxGnyqkU2lqUyx/1iXYyPLewika
  template:
    metadata:
      name: authentik-secrets
      namespace: authentik
    type: Opaque
