apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: grafana
  namespace: monitoring
  annotations:
    tailscale.com/funnel: "false"
    gethomepage.dev/enabled: "true"
    gethomepage.dev/name: Grafana
    gethomepage.dev/description: Metrics and dashboards
    gethomepage.dev/group: Infrastructure
    gethomepage.dev/icon: grafana.png
    gethomepage.dev/href: https://grafana.lungfish-ide.ts.net
    gethomepage.dev/app: grafana
spec:
  ingressClassName: tailscale
  tls:
    - hosts:
        - grafana
  rules:
    - host: grafana
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: kube-prometheus-stack-grafana
                port:
                  number: 80
