apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: nfs-backup
provisioner: nfs.csi.k8s.io
parameters:
  server: 192.168.178.39
  share: /volume1/k8s-backup
reclaimPolicy: Retain
volumeBindingMode: Immediate
mountOptions:
  - nfsvers=4
