apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: miniflux-backup
  namespace: miniflux
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: nfs-backup
  resources:
    requests:
      storage: 2Gi
