---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: miniflux-secrets
  namespace: miniflux
spec:
  encryptedData:
    database-password: AgBvsqxOS/RMkCw5Z55jwV+tl4RQAkplbrfTIgvoshHXp7v/5sYayKfcX5mLav7IKr6GvXy3MsSelbKgDhQXV+QYaQ4DRVJ4B7Tl1NnoFGsTf1N7qZIdPKvd4byf4NLCRQU5II8lJd+PtAFr99XbIY4nhBXAd2yr95dlfZjQQc2chkPy/w1J0CCmgs/o7Jq8ISuYdbYp1Wn8uZw/dXPchqZ/4nVwHNAxGShF/74oFR7FcKRhzmor/xxgB6tWejcn+LTDNzIDn7UQfHdQx9tirvnlprOP5qHtfYcXg0eM8glHZANs0yT4OuDrK/Z+VjOSHY7YYXkULxLAA2kE2BwCjiZUeRwgMF3TcLB8/zvsvSK2jsbXqSeWXfinoyPofvxxD+kO1KftFFSWNKfgQP5+7pE7UImdCjakvMNnwSjADmvYvmYLE0FOeQ/sgWbajFCTZ4Ghc3+3NVESQFtEgOap1lq1MtkD4QGJx8I4IYFK6NqU8LVMve3+/6enQPJhS83cMOjI0o3nAV6mTPm2jEfrslH9tdsZiikKX+8lLubuT3s++R/m0BvGLuluxLBW/hg659PEEa9b2KFKiFEaDf46eKlI2SZ6aTyMImCMDvCKSjUzV+u48Zg6eu+UmeKWjzjF8T9XY5bH7wGS/egbTDx108f/Un+xs8OcNmxcFtFVfOzk4ES8kZeDj5OP4ka32sFN9mczXS+OZHaniZYzpjSot5bphjPJnP/5HQD8KbaB0ajeG0TCEsGGRSp2zg==
    database-url: AgBoDCKeOJ2hHzcRFEpnzvQToQ0ahAp7OVy/uulmxUgCwKoVYExzoZDEImzG2b66SftsVzqfWJmaWo1nVk8THuKsDdsP9+HN5u2/zGSDBe0fEfXwGOX2noOhcBpIytxoZXEJLDzEfI5r9LI/aUjigYfW38SS8VMqBM52+ps8URbDvTzi6q2SrsW+IzvW1wUbEwZPvzxXTPd4m0sKdMDdmmx1ki5kC2G/ejKL3sF0dmkYygZZ9FCmXHnvT3f5MBIMV0DxhAvlJ+QNWaL9NU3XLdx+Jgk2RSPiNGD4yDl99D6aQCma3TDi/wg+IFGJOHrb8SVZFKLUc4vPUiUBFXCpt/xIsRdYl7K67UQnxWLO9HvZKMMSKZ72CKwLOC5fwdZeXxQbYGJf4HfG4kgh9AQj9VNkp99i/uW6hwuq/ewIUeIkL2gBmbHSvSXW0F/GjajRY9853egEU+IGrkj84z6AxTTa6MD336E6ItOzCPPdEK65KXE7jpy98jMkz2dUV9MArHzjgJMHS6BpXiAH7zg+NDHJmENhaal0w7YkVxcEfdUQqFVaYfPi53jc09o6nwODCCZ/VwhnR107cDWINA88UczNRzN9uxaPqQf/iowiGdeO7NqwXEy5rUTyoVlFRTfeeKUQ8lN4njlpapoKbRiBgX93FyFrLiVmi5yO0RCBjLOWG6h4dzRaQYOuHVfXCSobiW2yXp9NEEcH7dZGQKZChccnGX6jAgHu+lgLVhDk5T2IO95qP/+z/FD8lz394FtnbJHSgqXeD3TggGvdw5ctSLTrIjz5iV9CjctU3ZTJ+EgtuEJkFk9j5cxOdk8oOs60DIORUjL5qakYKw==
  template:
    metadata:
      name: miniflux-secrets
      namespace: miniflux
    type: Opaque
