apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: root
  namespace: argocd
spec:
  goTemplate: true
  generators:
    - list:
        elements:
          - app: argocd
            path: manifests/argocd
          - app: authentik
            path: manifests/authentik
          - app: mealie
            path: manifests/mealie
          - app: vikunja
            path: manifests/vikunja
          - app: it-tools
            path: manifests/it-tools
          - app: homepage
            path: manifests/homepage
          - app: paperless
            path: manifests/paperless
          - app: freshrss
            path: manifests/freshrss
  template:
    metadata:
      name: "{{.app}}"
      namespace: argocd
      finalizers:
        - resources-finalizer.argocd.argoproj.io
    spec:
      project: default
      source:
        repoURL: https://github.com/seakayone/homelab-k8s.git
        targetRevision: main
        path: "{{.path}}"
      destination:
        server: https://kubernetes.default.svc
        namespace: "{{.app}}"
      syncPolicy:
        automated:
          prune: true
          selfHeal: true
        syncOptions:
          - CreateNamespace=true
          - ServerSideApply=true
