apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: paperless-backup
  namespace: paperless
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: nfs-backup
  resources:
    requests:
      storage: 10Gi
