apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: paperless
  namespace: paperless
  annotations:
    tailscale.com/funnel: "false"
    gethomepage.dev/enabled: "true"
    gethomepage.dev/name: Paperless
    gethomepage.dev/description: Document management system
    gethomepage.dev/group: Productivity
    gethomepage.dev/icon: paperless-ngx.png
    gethomepage.dev/href: https://paperless.lungfish-ide.ts.net
    gethomepage.dev/app: paperless
    gethomepage.dev/pod-selector: app=paperless
spec:
  ingressClassName: tailscale
  rules:
    - host: paperless
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: paperless
                port:
                  number: 8000
  tls:
    - hosts:
        - paperless
