---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: paperless-secrets
  namespace: paperless
spec:
  encryptedData:
    database-password: AgACrEMFhi9VOAdY1y3dy/C9wYEKI7QgSlwJ3QkJvOErV36L41V/5a5xz8Xz11EejoCDMsn8Ji8k3rrt0zWmaLSOwdgD4h2YusQL1Ddgs4OFYNJHuo4DVF9Hd5AqBx95dR/ZheqZHH7YsqEjiMk1o7idyf4F1SjPFv/0Kw/6rt35PRZ+jduTSQ/YHHewEvx4PdjUwtLXejbjDDCKWuaSvazcjfNou1zXpWCqDDVr68NOiao0fU6bXZQfxnPxZ7yRpuDHyygZl5aegKcIowHDjPbAlBTenWxA8VSL3S8Mzeh0QqeqqeO/gt8jH2Dkc/uh+568szJREzbhLGeNbBy1XKh1hGYBKMlg3pIJJsI3AB0yq5069jrc2roYod30MAjH0yCPjYiPZhK8ybE+M9MxJxHhgcDXjhR/WHLjEV9pRAFy53GySMDURGhXKK1PDknaplYv+25NfPeHUPrKZ78Daj6n6MMZJHqUXuwT9GK+Y9gXg7Hl3rxeyIIbIorfL9AJrIU0jdmvg5xYgbylOaFkdXxIp8PJJ1YMsv0570U0Etflr559wXTFO8l5NZnhmz5af23cJy+bt6d83qrdcyef5mUxEIY5qE/a6DpKEBIjkf+ooqMR0HkZPdoBevIx/yMVhpDmzN/lm74+M4BLQMn33Y5Cv0S2iH4U158deBXgQJIsUoRlObOi/ezA1ASrB3XuRLccXX9y58YGG40RH4QG5NmU6hQ55wr3Sn79vdbwaCopxoVVdFn51BNFf5fsAA==
    secret-key: AgBHsx8Q5j+8lzHZaB1P5ivPz3+FxTjZqESkr7ODF52472VBqj1UioikB+wBsaManzt2er9iUO8hcGdsbcb5KIe58Afbsi9KDAO7XpVCdZAQ8ciLgubd8qTJWnJfzA80TOOH5qXobzCrYIpaUVGeVHBbzVxtFGYYgYpSLAJOG7Wi4QUk+I7yMD45k3DGVEf0XJ3eLnd5u01F9LZJgBX6FPLioLP0UqNNXk2vO/AFuL73NjVUo/FjEMkZZsWwHzkNFMAPpMnEWMTXEl6jn9LUxTGymx0hpU/DnGfqRhpx7qZyUO074zPT1EV/h6sphbegidcanTX3rWs5WVTaKK0QPvwk6kgMuXHzk0PZyyc4JsxDVdu3Yz/fo1DCZlHxgQA0hUPX5WDvMJ6OITHDWMkSahe38AmofvUMbjg3XH8seip2zVDj7Vf8SGzBAWPxGbG0kXckq718vlgvOZ9mKKHMfRq/K1EJ3kEhXgmB0+iPJ1OMhQUTdv63XYVQh/28unszpLjVzEzcVbOjlqTPqM/6Sq9tUAv9XIP/kE9r/noWky46/TPVMyueHO5UTEux4/H9XMZ6327SyrwOJRf+QtZ0zIDxhAVDADku2PeaJ5mWYk/RDohG9h7Cg6z2TrHb/kzN6d7QBbEAQD9SYVnbfbasqxECeE0n4qjdTwNzNDjW2zQFqBWI5t/svBQVg2K67g8gL4W9VI9i91Ze2Qk3IcX/W5WUTLtd9O2Jke9ts03+A2bxSDEJIssNVUk2Re2sLH2s1Qq46SOgc0qqIQf0OUNsSVoCzU7mLFWoJhoXKWthnEjWl+EMQOUK4jKMamfc+8BR3XXYIjdK
  template:
    metadata:
      name: paperless-secrets
      namespace: paperless
    type: Opaque
