---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: vaultwarden-secrets
  namespace: vaultwarden
spec:
  encryptedData:
    admin-token: AgBXf6KRAnr4ApYbsrcb/Gi4DZT4dDeERbnvVUtakC/7SIEJ8nghFl3JvqLp//cGBEp9m+PCrw5oOtDc7E70TMubVt3UnKrKRcdf0gkbDhyVJAIUod9dvkbBpu3xarc+p+odc9437/TPzMVIZTw+nvJHAPjE9WiCEI48a712u3R/C+NzrimiSAJfwgh/X7F4nbCWbE+yHGm7K8bNBYhComPaD4O5auzrZ62ETWqNnS8Kyz67IF6biPCuvhZAvN6ATixG+WwYfVXkhc4pDqjUuA0lNlwYQ9r7cEyu2GVRts5AC3Fbp7wOPK7QslbDYSNOxUReSNcmmv0DM93k8773HLP85vkslql+DrDibLn4ltlBOnxD7ViMJfNNiuerPVB8SBj2kyqUjx2cXwWVBJCIeWEl2Q1hy2fR8a2z0OLXb3ybYgAy71Sf6722UJ0mjcMHWNG373OMFyf77/Wihucnqnojf830VUEDpMFxPLKnOvkfYVYf1DXkRFM9JdqOQubEeK8CF+YGAi0t4qkAEvvXP0BK2rXXNm4jkWTUlCY+xKvijF+amc23ztm1mAeFQ0boqHTrBdncsNHhRhAjr/5rpiFmo3dzlMzGcevmpSFlsXWMmS1W/HHO+P7T6hDT9oVkwPNHF0Xf9A4F2GNNlcgw7uaptXmyON4mDqxtIY8U7bOzK4VvjUMIWTPAZnKuekUAitQ9SOBsBDRkqw==
  template:
    metadata:
      name: vaultwarden-secrets
      namespace: vaultwarden
    type: Opaque
